### ISSUE TITLE
How to Install in an Anaconda Environment?

### ISSUE THREAD

**Issue by TechVillain** [adang1345/PythonWin7#21]
Currently, I am using Anaconda in Windows 7 Pro for all my Python environments. Each environment is separate and independent for different software.

How do I install this repository in an Anaconda Environment, rather than the entire Windows 7 system?

Is there a way to build a wheel file (.whl) and then pip install that wheel to a conda environment?

**Comment by adang1345** [comment]
These packages do not support Anaconda, and releasing packages for Anaconda would be a major project that I'm not able to take on at this time. If you want an isolated Python environment, the closest you can get is with the embeddable zip file or NuGet package.

**Comment by TechVillain** [comment]
Could you please elaborate on how to use/install the embeddable zip file or the NuGet package?

So, I have several AI software working well on Python 3.8 in separate Anaconda environment. Then I have several new AI software requires Python 3.9 or above. I hope to run these new software on 3.9 without changing or disturbing the old ones that are already working smoothly on 3.8. What should I do?

Zip files are NOT the same as .whl or .tar.gz files, which can be pip installed, right? 

If I unzip the zip file, then copy paste the whole thing to an existing Anaconda env folder, is it going to make a huge mess?

If you were in my situation, what would you do to have both 3.8 and 3.9 running on the same Windows 7 computer?

**Comment by adang1345** [comment]
I don't have much experience with Anaconda, so I can't say what you can do with your Anaconda environments.

I see two options for you.
- Run the Windows installer for Python 3.9 or above and install it system-wide. There should be ways to ensure that the system-installed Python does not interfere with the Anaconda environments; you'll need to do your own research about how to ensure this and might need to test things out yourself. I actually have multiple versions of Python installed system-wide on my computer, all using the Windows installer.
- Install the NuGet package, which does put Python in its own isolated environment. See https://github.com/adang1345/PythonWin7#nuget-packages for instructions on how to install a NuGet package. The documentation at https://docs.python.org/3/using/windows.html#the-nuget-org-packages also provides more information about the NuGet packages in general.

Another thing to be careful of is whether the AI software you plan to use for Python 3.9+ will work on Windows 7. Since Python 3.9+ is not officially supported on Windows 7, third-party libraries that target Python 3.9+ might not work on Windows 7. This might be something you'll need to test yourself.

**Comment by TechVillain** [comment]
First, this NuGet method you mentioned could possibly be a game changer. I will do some extensive research and test and then report back.

Second, you mentioned that you have multiple versions of Python installed system-wide on your computer, all using the Windows installer. How did you do this? Could you elaborate on your method?

Third, the best method would be, download VirtualBox and simply install a Windows 10 virtual machine inside Windows 7 system. However, I don't want to go down this path, because it's a hassle to start a virtual machine everytime you need to run some Python, and Windows 10 is bloated and takes lots of hard drive for nothing.

Fourth, how hard is it to create a .whl or .tar.gz file for your custom Python 3.9? Just like PyTorch, with a whl or tar file, you can easily pip install it however you want, wherever you want. You don't have to complie all versions, just do a wheel for 3.9.0, then you saved the world.

Fifth, Anaconda or Miniconda is nothing but a virtual environment isolator. You install it, create a virtual environment with official Python, active that environment, then uninstall the official one and reinstall the custom one, easy. The only thing it needs, is a wheel or a tarball file.

Sixth, PyTorch 2.0.0 already dropped support for Python 3.7, which means, 3.8 will be the next they murder. The clock is ticking, and hopefully you can come up with something about 3.9-Win7, before the world ends.

Seventh, millions of people in the AI community are using Anaconda for seperating envs, it is the industry standard, and a large portion of these people are still holding onto Windows 7, of which is the most efficient OS in the US history. I hope you could consider, giving these people a gift of your custom Python, for the upcoming Christmas, to warm up their hearts.

**Comment by adang1345** [comment]
These are all good questions, but they are outside the scope of what this repository provides, and I'm not the right person to answer them. The goal of this repository is specifically to get core Python 3.9+ working on Windows 7. I can't provide much consultation beyond that goal.
